server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/news-feed-app?authSource=admin
  cloud:
    config:
      enabled: false

aws:
  s3:
    region: ap-south-1
    bucket: news.feed-media-service
    endpoint: https://s3.ap-south-1.amazonaws.com
    access-key: #{access-key}
    secret-key: #{secret-key}
    cdn-url: ${CDN_URL:https://cdn.my-social.com}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  template:
      default-topic: media-events

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
